language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get update
 - sudo apt-get install libblas-dev
 - sudo apt-get install liblapack-dev
 - sudo apt-get install gfortran
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
